Selenium locator type compatibility for web view
appium/python-client pull request #724
Opened 2022-06-13 14:46 UTC by VladimirPodolyan

Hi! I faced with an issue while using `appium.find_element` with locators, that I used for my selenium tests. Is it possible to uncomment that block and use him in `web view` context only ?

2022-06-13 15:38 UTC, mykola-mokhnach requested changes
see the above comment

2022-06-13 16:27 UTC, VladimirPodolyan commented
@mykola-mokhnach Hi, and thank you for answer. 
So, maybe it's possible to pass that as class argument **for both classes**? 

For WebDriver:
```python
class WebDriver(...):
    def __init__(command_executor, desired_capabilities, ..., selenium_compatibility)
        ...
        self.selenium_compatibility = selenium_compatibility

    def find_element():
            if self.selenium_compatibility:
                if by == By.ID:
                    ...
```
For WebElement (need to define `__init__`)
```python
class WebElement(AppiumWebElementSearchContext):
    def __init__(self, selenium_compatibility=False):
        self.selenium_compatibility = selenium_compatibility

    def find_element():
            if self.selenium_compatibility:
                if by == By.ID:
                    ...
```

Or only for `WebDriver`, even you don't accept the specifying the `__init__` in WebElement

2022-06-14 11:42 UTC, VladimirPodolyan commented
@mykola-mokhnach Understood. But what is the final decision here? You don't want to have this "Selenium workaround" in your own code, but it's commented right now. Can I just delete this "comment section" in this PR and do a self workaround in my side?

2022-06-14 18:33 UTC, mykola-mokhnach commented on appium/webdriver/webdriver.py
> +        # Let's keep it for future support of the selenium workaround
I'd rather change the comment to `We prefer to patch locators in the client code. Checking current context every time a locator is accessed could significantly slow down tests`

2022-06-14 19:20 UTC, mykola-mokhnach approved these changes

2022-06-15 01:28 UTC, KazuCocoa approved these changes

2022-06-15 01:28 UTC, merged